=== ubuntudroid/WatchMyPhone/MobilisServer/src/META-INF/MobilisSettings.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="setting">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="setting" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="settings">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setting" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="agent">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="description" type="xs:string" use="required" />
			<xs:attribute name="type" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="start" use="optional" default="auto">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="auto" />
						<xs:enumeration value="ondemand" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="agents">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="agent" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="description" type="xs:string" use="required" />
			<xs:attribute name="type" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="agent" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="start" use="optional" default="auto">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="auto" />
						<xs:enumeration value="ondemand" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="network">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" type="xs:NMTOKEN" use="required" />
			<xs:attribute name="description" type="xs:string" use="required" />
			<xs:attribute name="type" type="xs:NMTOKEN" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="networks">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="network" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="agents" />
				<xs:element ref="services" />
				<xs:element ref="networks" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


</xs:schema>

=== ubuntudroid/WatchMyPhone/MobilisServer/wmp_server_config/MobilisSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="MobilisSettings.xsd">
	<agents>
	
		<agent name="buddy" description="Buddy Broker Service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Buddy</setting>
			</settings>
		</agent>
		<agent name="coordinator" description="Coordinator"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Coordinator</setting>
			</settings>
		</agent>
		<agent name="context" description="User Context Broker Service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Context</setting>
			</settings>
		</agent>
		<agent name="collabediting" description="Collaborative Editing Broker service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">CollabEditing</setting>
			</settings>
		</agent>
		<agent name="content" description="Default Content Broker service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Content</setting>
			</settings>
		</agent>
		<agent name="repository" description="Repository Broker Service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Repository</setting>
			</settings>
		</agent>
		<agent name="grouping" description="Grouping Broker Service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">Grouping</setting>
			</settings>
		</agent>
		
		<agent name="locpairsHTTP" description="locpairs HTTP server"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="auto">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">LocPairsHTTP</setting>
			</settings>
		</agent>
		
		<agent name="locpairs" description="locpairs game server service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="ondemand">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">LocPairs</setting>
			</settings>
		</agent>
		
		<agent name="xhunt" description="xhunt game server service"
			type="de.tudresden.inf.rn.mobilis.server.agents.MobilisAgent" start="ondemand">
			<settings>
				<setting name="host">79.125.77.206</setting>
				<setting name="port">5222</setting>
				<setting name="service">79.125.77.206</setting>
				<setting name="username">mobilis</setting>
				<setting name="password">mobilis</setting>
				<setting name="resource">XHunt</setting>
			</settings>
		</agent>
		
	</agents>
	<services>
		<service name="ContextService" description="Context Service"
			type="de.tudresden.inf.rn.mobilis.server.services.ContextService"
			agent="buddy" start="auto" />
		<service name="BuddyFinderService" description="Buddy Finder Service"
			type="de.tudresden.inf.rn.mobilis.server.services.BuddyFinderService"
			agent="buddy" start="auto">
			<settings>
				<setting name="Radius">500</setting>
				<setting name="Status">true</setting>
			</settings>
		</service>
		<service name="SocialNetworkIntegrationService" description="Social Network Integration Service"
			type="de.tudresden.inf.rn.mobilis.server.services.SocialNetworkIntegrationService"
			agent="buddy" start="auto" />
		<service name="SessionService" description="Session Service"
			type="de.tudresden.inf.rn.mobilis.server.services.SessionService"
			agent="coordinator" start="auto">
			<settings>
				<setting name="PubSubServer">pubsub.79.125.77.206</setting>
				<setting name="PubSubNode">testnode0</setting>
				<setting name="ChatRoomServer">conference.79.125.77.206</setting>
			</settings>
		</service>
		<service name="CollabEditingService" description="Collaborative Editing Service"
			type="de.tudresden.inf.rn.mobilis.server.services.CollabEditingService"
			agent="collabediting" start="auto">
			<settings>
				<setting name="ChatRoomServer">conference.79.125.77.206</setting>
			</settings>
		</service>
		<service name="RepositoryService" description="Repository Service"
			type="de.tudresden.inf.rn.mobilis.server.services.media.RepositoryService"
			agent="repository" start="auto">
			<settings>
				<setting name="ContentBroker">mobilis@79.125.77.206/Content</setting>
				<setting name="Slices">
					<setting name="taken">timestamp</setting>
					<setting name="longitude_e6">integer</setting>
					<setting name="latitude_e6">integer</setting>
					<setting name="description">string</setting>
					<setting name="title">string</setting>
					<setting name="owner">string</setting>
				</setting>
			</settings>
		</service>
		<service name="ContentService" description="Default Content Service"
			type="de.tudresden.inf.rn.mobilis.server.services.media.ContentService"
			agent="content" start="auto">
			<settings>
				<setting name="StorageFolder">store/ContentService</setting>
			</settings>
		</service>
		<service name="GroupingService" description="Grouping Service"
			type="de.tudresden.inf.rn.mobilis.server.services.grouping.GroupingService"
			agent="grouping" start="auto">
			<settings>
				<setting name="ChatRoomServer">conference.79.125.77.206</setting>
			</settings>
		</service>
		<service name="CoordinatorService" description="Coordinator Service"
			type="de.tudresden.inf.rn.mobilis.server.services.CoordinatorService"
			agent="coordinator" start="auto">
		</service>
		<service name="UserContextService" description="User Context Service"
			type="de.tudresden.inf.rn.mobilis.server.services.context.UserContextService"
			agent="context" start="auto">
		</service>
		<service name="LocPairsHTTPServer" description="The service starts an http-server to provide access to the xml files generated in the game LocPairs"
			type="de.tudresden.inf.rn.mobilis.server.services.locpairs.LocPairsHTTPServer"
			agent="locpairsHTTP" start="auto">
		</service>
		
		<service name="LocPairs" description="The service starts an http-server to provide access to the xml files generated in the game LocPairs"
			type="de.tudresden.inf.rn.mobilis.server.services.locpairs.LocPairs"
			agent="locpairs" start="ondemand">
		</service>
		
		<service name="XHunt" description="Xhunt Service"
			type="de.tudresden.inf.rn.mobilis.server.services.xhunt.XHunt"
			agent="xhunt" start="ondemand">
		</service>
		
	</services>
	<networks>
		<network name="facebook" description="Facebook Integration Service"
			type="de.tudresden.inf.rn.mobilis.server.services.integration.FacebookIntegrationService">
			<settings>
				<setting name="apikey">193b0ef6780660b193b04407ddc84c27</setting>
				<setting name="secret">5908a4bc82adcc3052b7e9ec1e738999</setting>
				<setting name="trackable">false</setting>
			</settings>
		</network>
		<network name="addressbook" description="Addressbook Integration Service"
			type="de.tudresden.inf.rn.mobilis.server.services.integration.DefaultIntegrationService">
			<settings>
				<setting name="trackable">false</setting>
			</settings>
		</network>
		<network name="roster" description="Roster Integration Service"
			type="de.tudresden.inf.rn.mobilis.server.services.integration.DefaultIntegrationService">
			<settings>
				<setting name="trackable">true</setting>
			</settings>
		</network>
	</networks>
</config>
